### ISSUE TITLE
question: What is ramba:ramba?

### ISSUE THREAD

**Issue by escaroda** [ccorcos/meteor-viz-deps#1]
What is it you have in packages called ramba:ramba?
Can't find anything about it

**Comment by ccorcos** [comment]
haha. maybe because you're spelling it wrong ;) [ramDa](http://ramdajs.com/0.15/docs/).

Ramda is really quite awesome. I highly recommend it. Its brings a lot of functional programming patterns to Javascript. Pure, point-free, composable, curried functions and immutable data. Check out the talk here:

https://www.youtube.com/watch?v=m3svKOdZijA&app=desktop

And this more extended post about why/how to use ramda:

http://fr.umio.us/why-ramda/
